EFF/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('userapp/',include('userapp.urls')),
    path('operations/',include('operations.urls')),
]

operations/urls.py
from django.urls import path

from operations import views

app_name='operations'

urlpatterns=[
    path('show/',views.show,name='show'),
    path('addgood/',views.addgood,name='addgood'),
    path('addgoodlogic/',views.addgood_logic,name='addgoodlogic'),
    path('together/',views.together,name='together'),
    path('addpurchase/',views.add_purchase_record,name='addpurchase'),
    path('addpurchaselogic/',views.add_purchase_logic,name='addpurchaselogic'),
    path('modify/',views.modify,name='modify'),
    path('modifylogic/',views.modify_logic,name='modifylogic'),
    path('dele/',views.dele,name='dele'),
    path('purchase/',views.purchase,name='purchase'),
    path('return_purchase/',views.return_purchase,name='return_purchase'),
    path('employees/',views.employees,name='employees'),
    path('addemployee/',views.addemployee,name='addemployee'),
    path('addemployeelogic/',views.addemployee_logic,name='addemployeelogic'),
    path('deleemployee/',views.dele_employee,name='deleemployee'),
    path('delepurchase/',views.dele_purchase,name='delepurchase'),
    path('delereturnpurchase/',views.dele_returnpurchase,name='delereturnpurchase'),
    path('modifyemp/',views.modify_employee,name='modifyemp'),
    path('modifyemplogic/',views.modifyepm_logic,name='modifyemplogic'),
    path('select/',views.select,name='select'),
    path('select1/',views.select1,name='select1'),
]

userapp/urls.py
from django.urls import path
from userapp import views
app_name='userapp'

urlpatterns=[
    path('register/',views.register,name='register'),
    path('registerlogic/',views.register_logic,name='registerlogic'),
    path('checkname/',views.check_name,name='checkname'),
    path('setimg/',views.setImage,name='setimg'),
    path('captchlogic/',views.captch_logic,name='captchlogic'),
    path('login/',views.login,name='login'),
    path('loginlogic/',views.login_logic,name='loginlogic'),
    path('home/',views.home,name='home'),
    path('forget_pwd/', views.forget_pwd, name='forget_pwd'),
    path('forgetpwdlogic/', views.forget_pwd_logic, name='forgetpwdlogic'),
    path('resetpwd/', views.reset_pwd, name='resetpwd'),
    path('resetpwdlogic/', views.reset_pwd_logic, name='resetpwdlogic'),
    path('logout/',views.logout,name='logout'),
    path('active/', views.active, name='active'),
    path('reactive/', views.reactive, name='reactive'),
]

operations/models.py
from django.db import models

# Create your models here.
class Employees(models.Model):
    name=models.CharField(max_length=30)
    sex=models.CharField(max_length=30)
    age=models.IntegerField()
    tel=models.CharField(max_length=30)
    position=models.CharField(max_length=30)
    class Meta:
        db_table='tb_employees'

class ReturnSale(models.Model):
    name=models.CharField(max_length=30)
    data=models.DateTimeField()
    num = models.IntegerField(null=False)
    address = models.CharField(max_length=80)
    content = models.TextField()
    class Meta:
        db_table='tb_returnsale'

class GoodCate(models.Model):
    good_cate_name=models.CharField(max_length=30)
    parent_id=models.IntegerField()
    level=models.IntegerField()
    class Meta:
        db_table='tb_goodcate'

class Good(models.Model):
    name = models.CharField(max_length=30, null=False)
    good_name = models.CharField(max_length=30, null=False)
    date = models.DateTimeField(null=False)
    content = models.TextField(null=False)
    sell_num = models.IntegerField(null=False)
    good_id = models.ForeignKey(to=GoodCate, on_delete=models.DO_NOTHING, null=False)
    class Meta:
        db_table = 'tb_good'

class Purchase_records(models.Model):
    name=models.CharField(max_length=30)
    data=models.DateTimeField()
    num=models.IntegerField(null=False)
    address=models.CharField(max_length=80)
    content=models.TextField()
    class Meta:
        db_table='tb_purchase_records'

operations/views.py
from django.core.paginator import Paginator
from django.db import transaction
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from operations.models import GoodCate, Good, Purchase_records, ReturnSale, Employees


def show(request):
    status = request.session.get('login')
    if status:
        num = request.GET.get('id')
        cate_name = GoodCate.objects.filter(level=1)
        good_name =GoodCate.objects.filter(level=2)
        sell_num = request.GET.get('sell_num')
        times = request.GET.get('times')
        employee=request.GET.get('employee')
        good_name1 = request.GET.get('good_name')
        two_name = request.GET.get('two_name')
        three_name = request.GET.get('three_name')
        print(sell_num,times)
        if not num:
            num = 1
        if sell_num:
            good=Good.objects.all().order_by('-sell_num')
            paginator = Paginator(good, per_page=5)
            pg = paginator.page(num)
            print(pg.object_list)

            return render(request, 'operations/home.html', {'good': pg,
                                                            'cate_name': cate_name,
                                                            'good_name': good_name,
                                                            'three_name': three_name,
                                                            'two_name': two_name,
                                                            'good_name1': 'good_name1',
                                                            'times': 'times',
                                                            'sell_num': 'sell_num'})
        if times:
            good=Good.objects.all().order_by('-date')
            paginator = Paginator(good, per_page=5)
            pg = paginator.page(num)
            print(pg.object_list)
            return render(request, 'operations/home.html', {'good': pg,
                                                            'cate_name': cate_name,
                                                            'good_name': good_name,
                                                            'three_name': three_name,
                                                            'two_name': two_name,
                                                            'good_name1': 'good_name1',
                                                            'times': 'times',
                                                            'sell_num': 'sell_num'})
        if good_name1:
            good1_id=GoodCate.objects.filter(good_cate_name=good_name1)[0].id
            good=Good.objects.filter(good_id_id=good1_id)
        if two_name:
            id1 = GoodCate.objects.filter(good_cate_name=two_name)[0].id
            class_id =GoodCate.objects.filter(parent_id=id1)
            list_id = []
            for i in class_id:
                list_id.append(i.id)
            for j in list_id:
                # j 文章表中的的class+id 来查询所属文章
                good1 = Good.objects.filter(parent_id=j)
            good =good1
        if three_name:
            id2 = GoodCate.objects.filter(good_cate_name=three_name)[0].parent_id
            id3 = GoodCate.objects.filter(good_cate_name=three_name)[0].id
            # 覆盖掉一级标题
            two_name = GoodCate.objects.filter(pk=id2)[0].good_cate_name
            # 通过id3查询二级标题的文章
            good = Good.objects.filter(good_id_id=id3)
        else:
            good=Good.objects.all()
        paginator = Paginator(good, per_page=5)
        pg = paginator.page(num)
        print(pg.object_list)
        return render(request, 'operations/home.html',{'good':pg,
                                                       'cate_name':cate_name,
                                                       'good_name':good_name,
                                                       'three_name': three_name,
                                                       'two_name': two_name,
                                                       'good_name1':'good_name1',
                                                       'times':'times',
                                                       'sell_num':'sell_num'})
    else:
        return redirect('userapp:login')

def addgood(request):
    cate_name=GoodCate.objects.filter(level=1)
    good_name = GoodCate.objects.filter(level=2)
    return render(request,'operations/addGood.html',{'cate_name':cate_name,
                                                     'good_name':good_name})
#添加商品逻辑
def addgood_logic(request):
    try:
        name=request.POST.get('goodname')
        cate_name=request.POST.get('cate_sel')
        good_name=request.POST.get('good_sel')
        date = request.POST.get('date')
        text = request.POST.get('text')
        id = GoodCate.objects.filter(good_cate_name=good_name)[0].id
        print(id,name,cate_name,good_name,date,text)
        rst=Good.objects.create(name=name,good_name=good_name,date=date,content=text,good_id_id=id)
        if rst:
            return JsonResponse({'msg': '恭喜添加成功', 'status': 1})
        else:
            return JsonResponse({'msg': '添加失败', 'status': 0})
    except:
        return JsonResponse({'msg':'添加失败','status':0})

def addemployee(request):
    cate_name = GoodCate.objects.filter(level=1)
    good_name = GoodCate.objects.filter(level=2)
    return render(request, 'operations/add_employee.html', {'cate_name': cate_name,
                                                       'good_name': good_name})
#添加员工逻辑
def addemployee_logic(request):
    try:
        name=request.POST.get('name')
        sex=request.POST.get('gender')
        age=request.POST.get('age')
        tel=request.POST.get('tel')
        position=request.POST.get('position_sel')
        print(name,sex,age,tel,position)
        rst=Employees.objects.create(name=name,sex=sex,age=age,tel=tel,position=position)
        if rst:
            return JsonResponse({'msg': '恭喜添加成功', 'status': 1})
        else:
            return JsonResponse({'msg': '添加失败', 'status': 0})
    except:
        return JsonResponse({'msg': '添加失败', 'status': 0})

#二级联动
def together(request):
    name = request.GET.get('name')
    # 获取 good表的数据,名称和等级
    id =GoodCate.objects.filter(good_cate_name=name)[0].id
    class_name = GoodCate.objects.filter(parent_id=id)
    a = []
    for i in class_name:
        a.append(i.good_cate_name)
    return JsonResponse({'msg': a})

def add_purchase_record(request):
    cate_name=GoodCate.objects.filter(level=1)
    good_name = GoodCate.objects.filter(level=2)
    return render(request,'operations/addpurchase_record.html',{'cate_name':cate_name,
                                                                'good_name':good_name})
#添加进货记录
def add_purchase_logic(request):
    try:
        with transaction.atomic():
            name = request.POST.get('purchasename')
            date = request.POST.get('date')
            num = request.POST.get('num')
            address = request.POST.get('address')
            content = request.POST.get('text')
            print(name, date, num, address, content)
            rst=Purchase_records.objects.create(name=name,data=date,num=num,address=address,content=content)
            if rst:
                return JsonResponse({'msg': '添加成功1', 'status': 1})
            else:
                return JsonResponse({'msg': '添加失败', 'status': 0})
    except:
        return JsonResponse({'msg': '添加失败', 'status': 0})

def modify(request):
    id1 = request.GET.get('id1')
    request.session['id']=id1
    good=Good.objects.get(id=id1)
    cate_name = GoodCate.objects.filter(level=1)
    good_name = GoodCate.objects.filter(level=2)
    return render(request,'operations/modify.html',{'good':good,
                                                    'cate_name':cate_name,
                                                    'good_name':good_name})
#修改商品逻辑
def modify_logic(request):
    id=request.session.get('id')
    name=request.POST.get('goodname')
    good_name=request.POST.get('good_sel')
    num=request.POST.get('num')
    date=request.POST.get('date')
    content=request.POST.get('text')
    good=Good.objects.get(id=id)
    print(id,name,good_name,num,date,content)
    try:
        with transaction.atomic():
            if good:
                good.name=name
                good.good_name=good_name
                good.date=date
                good.sell_num=num
                good.content=content
                good.save()
                return JsonResponse({'msg':'修改商品成功','status':1})
    except:
        return JsonResponse({'msg':'此商品不存在','status':0})

def modify_employee(request):
    id1 = request.GET.get('id7')
    request.session['id7']=id1
    emp=Employees.objects.get(id=id1)
    cate_name = GoodCate.objects.filter(level=1)
    good_name = GoodCate.objects.filter(level=2)
    return render(request,'operations/modify_employee.html',{'emp':emp,
                                                    'cate_name':cate_name,
                                                    'good_name':good_name})
#修改员工逻辑
def modifyepm_logic(request):
    id=request.session.get('id7')
    name=request.POST.get('name')
    position=request.POST.get('position_sel')
    age=request.POST.get('age')
    sex=request.POST.get('sex')
    tel=request.POST.get('tel')
    emp=Employees.objects.get(id=id)
    print(id,name,position,sex,age,tel)
    try:
        with transaction.atomic():
            if emp:
                emp.name=name
                emp.sex=sex
                emp.age=age
                emp.position=position
                emp.tel=tel
                emp.save()
                return JsonResponse({'msg':'修改员工信息成功','status':1})
    except:
        return JsonResponse({'msg':'此员工不存在','status':0})
#删除商品逻辑
def dele(request):
    try:
        with transaction.atomic():
            id=request.GET.get('id2')

templates/operations/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="utf-8"/>
    <!--<meta name="viewport"-->
          <!--content="width=device-width,initial-scale=1,minimum-scale=1,maximum-scale=1,user-scalable=no"/>-->
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.css"/>
    <link rel="stylesheet" href="/static/css/bodymain.css">
    <link rel="stylesheet" href="/static/css/home.css">
    <title>EFF超市管理系统-首页
    </title>
    <style>
         .breadcrumb{
             display: none;
         }
        #three{
            display: none;
        }
    </style>
</head>
<body>
<!--导航-->
<nav class="navbar navbar-default nav-self">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">EFF超市管理系统</a>
        </div>
        <div class="collapse navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'userapp:login' %}" role="button">登录 <span class="glyphicon glyphicon-log-in"></span></a>
                </li>
                <li>
                    <a href="{% url 'userapp:logout' %}">退出 <span class="glyphicon glyphicon-log-out"></span></a>
                </li>
            </ul>
            <form class="navbar-form navbar-right" action="{% url 'operations:select1' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input type="text" name="rst" class="form-control" placeholder="请输入你要搜索的内容">
                </div>
                <div class="btn-group" role="group" aria-label="...">
                    <div class="btn-group" role="group">
                        <button type="button" onclick="select()" class="btn btn-default dropdown-toggle" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">
                            <span class="glyphicon glyphicon-search"></span>
                        </button>
                    </div>
                </div>
            </form>

        </div>
    </div>
</nav>
<!--内容面板-->
<div class="container-fluid">
    <div class="row">
        <!-- Nav tabs -->
        <div class="panel-group col-sm-2 left-side-bar" id="accordion" role="tablist" aria-multiselectable="true">
            <div>
                <div class="panel panel-default">
                  <div class="panel-heading left-side-header"><a href="{% url 'operations:show' %}">EFF商品</a></div>
                    {% for foo in cate_name %}
                        <h5 class="course-python"><a href="{% url 'operations:show' %}?two_name={{ foo.good_cate_name }}" class="header">{{ foo.good_cate_name }}</a></h5>
                        <div class="list-group">
                            {% for foo1 in good_name %}
                                {% if foo1.parent_id == foo.id %}
                                    <a href="{% url 'operations:show' %}?three_name={{ foo1.good_cate_name }}" class="list-group-item">{{ foo1.good_cate_name }}</a>
                                {% endif %}
                            {% endfor %}
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <!-- Tab panes 详情展示面板 -->
        <div class="tab-content col-sm-10 right-side">

            <div class="panel panel-default right-side-content">
                <ol class="breadcrumb" id="ol">
                    <li><a href="JavaScript:void(0)">EFF超市商品</a></li>
                    <li><a href="{% url 'operations:show' %}?two_name={{ two_name }}">{{two_name}}</a></li>
                    <span style="color: silver">&nbsp;&nbsp;/&nbsp;&nbsp;</span>
                    <li><a href="{% url 'operations:show' %}?three_name={{ three_name }}" id="three">{{three_name}}</a></li>
                </ol>
                <div class="page-header">
                  <h3>商品信息</h3>
                </div>
                <div class="panel-body caret_parent">
                    <a href="{% url 'operations:show' %}?sell_num=1" class="btn btn-default">销售量<span class="glyphicon glyphicon-arrow-down"></span></a>
                    <a href="{% url 'operations:show' %}?times=2" class="btn btn-default">发布时间 <span class="glyphicon glyphicon-arrow-down"></span></a>
                    <a href="{% url 'operations:purchase' %}" class="btn btn-default">进货记录</a>
                    <a href="{% url 'operations:return_purchase' %}" class="btn btn-default">退货记录</a>
                    <a href="{% url 'operations:employees' %}" class="btn btn-default">员工信息</a>
                    <a href="{% url 'operations:addemployee' %}" class="btn pull-right base-color add-course"><span class="glyphicon glyphicon-plus"></span> 增加员工</a>
                    <a href="{% url 'operations:addgood' %}" class="btn pull-right base-color add-course"><span class="glyphicon glyphicon-plus"></span> 增加商品</a>
                    <a href="{% url 'operations:addpurchase' %}" class="btn pull-right base-color"><span class="glyphicon glyphicon-plus"></span> 增加进货记录</a>
                </div>
                <div class="panel-heading">商品列表</div>
                <table class="table table-bordered table-striped table-hover">
                    <thead>
                        <tr>
                            <th><input type="checkbox"/></th>
                            <th>ID</th>
                            <th>商品名称</th>
                            <th>所属商品分类</th>
                            <th>发布日期</th>
                            <th>销售量</th>
                            <th>操作</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for foo in good.object_list %}
                            <tr>
                                <td><input type="checkbox" class="checks"/></td>
                                <td>{{ foo.id }}</td>
                                <td>
                                    <a href="{% url 'operations:modify' %}?id1={{ foo.id }}">{{ foo.name }}</a>
                                </td>
                                <td>{{ foo.good_name }}</td>
                                <td>
                                    {{ foo.date }}
                                </td>
                                <td>
                                    {{ foo.sell_num }}
                                </td>
                                <td>
                                    <a href="{% url 'operations:dele' %}?id2={{ foo.id }}" class="btn btn-warning" onclick="return confirm('确认删除该商品吗?')">删除</a>
                                </td>
                            </tr>
                        {% endfor %}

                    </tbody>
                </table>
                <nav aria-label="Page navigation" class="pull-right pagitor-manager">
                    <ul class="pagination">
                        <li>
                           {% if good.has_previous %}
                                <a href="{% url 'operations:show' %}?id={{ good.previous_page_number }}&times={{ times }}&sell_num={{ sell_num }}&good_name1={{ good_name1 }}" aria-label="Previous">
                                <span aria-hidden="true">&laquo;</span>
                                </a>
                           {% endif %}
                        </li>
                        {% for foo in good.paginator.page_range %}
                            <li>
                                <a href="{% url 'operations:show' %}?id={{ foo }}&times={{ times }}&sell_num={{ sell_num }}&good_name1={{ good_name1 }}">
                                    {% if good.number == foo %}
                                        <span style="background-color: yellowgreen">{{ foo }}</span>
                                    {% else %}
                                        <span>{{ foo }}</span>
                                    {% endif %}
                                </a>
                            </li>
                        {% endfor %}
                        <li>
                            {% if good.has_next %}
                                 <a href="{% url 'operations:show' %}?id={{ good.next_page_number }}&times={{ times }}&sell_num={{ sell_num }}&good_name1={{ good_name1 }}" aria-label="Next">
                                <span aria-hidden="true">&raquo;</span>
                            </a>
                            {% endif %}
                        </li>
                    </ul>
                </nav>
            </div>
            <!--分页显示-->
        </div>

    </div>

</div>
<div class="footer">
    <div class="container">
        <div class="row">
            <div class="col-sm-4">
                <div class="thumbnail">
                  <div class="caption">
                    <h4><span class="glyphicon glyphicon-heart-empty glyphicon"></span> 关注我们</h4>
                    <p>最受欢迎的管理平台</p>
                    <p><a href="#" class="ic_df"> 新浪微博</a> </p>
                    <p><a href="#" class="ic_weichat"> 官方微信</a> </p>
                  </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="thumbnail">
                  <div class="caption">
                    <h4><span class="glyphicon glyphicon-king"> 开发平台</span> </h4>
                    <p>加入开发平台，尊享会员福利，成为资深程序猿</p>
                    <p class="p_idea"><a href="#"  class="btn btn-default btn-lg idea">我要开发</a></p>
                  </div>
                </div>
            </div>
            <div class="col-sm-4">
                <div class="thumbnail">
                  <div class="caption">
                    <h4><span class="glyphicon glyphicon-phone-alt"></span> 关于我们</h4>
                    <p>欢迎反馈宝贵意见</p>
                    <p class="p_idea"><a href="#"  class="btn btn-default btn-lg idea">意见反馈</a></p>
                  </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 cp_info">
                <div class="no-mp">
                    <p>CopyRight © 2020 上知天文下知科技有限公司 All Rights Reserved</p>
		            <p>电话：010-****888    豫ICP备*******8号</p>
                    <p class="p_idea"><a href="#top" class="btn btn-default btn-lg idea">回到顶部</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
<script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
<script>

     {#点击白纸课程掩藏#}
    $('#baizhi_class').click(function () {
        $('.breadcrumb ').css("display","");
    });

    {% if two_name %}
        $('.breadcrumb ').css("display","block");
    {% endif %}

    {% if three_name %}
        $('#three ').css("display","block");
    {% endif %}

    function select() {
        $.ajax({
            type:'post',
            url:'{% url "operations:select1" %}',
            data:$('form').serialize(),
            success:function (data) {
                if (data.status === 1){
                    alert(data.msg);
                    location.href="{% url 'operations:select' %}";
                }else {
                    alert(data.msg);
                }
            }
        })
    }
</script>


</body>
</html>