EFF/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('userapp/',include('userapp.urls')),
    path('operations/',include('operations.urls')),
]

operations/urls.py
from django.urls import path

from operations import views

app_name='operations'

urlpatterns=[
    path('show/',views.show,name='show'),
    path('addgood/',views.addgood,name='addgood'),
    path('addgoodlogic/',views.addgood_logic,name='addgoodlogic'),
    path('together/',views.together,name='together'),
    path('addpurchase/',views.add_purchase_record,name='addpurchase'),
    path('addpurchaselogic/',views.add_purchase_logic,name='addpurchaselogic'),
    path('modify/',views.modify,name='modify'),
    path('modifylogic/',views.modify_logic,name='modifylogic'),
    path('dele/',views.dele,name='dele'),
    path('purchase/',views.purchase,name='purchase'),
    path('return_purchase/',views.return_purchase,name='return_purchase'),
    path('employees/',views.employees,name='employees'),
    path('addemployee/',views.addemployee,name='addemployee'),
    path('addemployeelogic/',views.addemployee_logic,name='addemployeelogic'),
    path('deleemployee/',views.dele_employee,name='deleemployee'),
    path('delepurchase/',views.dele_purchase,name='delepurchase'),
    path('delereturnpurchase/',views.dele_returnpurchase,name='delereturnpurchase'),
    path('modifyemp/',views.modify_employee,name='modifyemp'),
    path('modifyemplogic/',views.modifyepm_logic,name='modifyemplogic'),
    path('select/',views.select,name='select'),
    path('select1/',views.select1,name='select1'),
]

userapp/urls.py
from django.urls import path
from userapp import views
app_name='userapp'

urlpatterns=[
    path('register/',views.register,name='register'),
    path('registerlogic/',views.register_logic,name='registerlogic'),
    path('checkname/',views.check_name,name='checkname'),
    path('setimg/',views.setImage,name='setimg'),
    path('captchlogic/',views.captch_logic,name='captchlogic'),
    path('login/',views.login,name='login'),
    path('loginlogic/',views.login_logic,name='loginlogic'),
    path('home/',views.home,name='home'),
    path('forget_pwd/', views.forget_pwd, name='forget_pwd'),
    path('forgetpwdlogic/', views.forget_pwd_logic, name='forgetpwdlogic'),
    path('resetpwd/', views.reset_pwd, name='resetpwd'),
    path('resetpwdlogic/', views.reset_pwd_logic, name='resetpwdlogic'),
    path('logout/',views.logout,name='logout'),
    path('active/', views.active, name='active'),
    path('reactive/', views.reactive, name='reactive'),
]

userapp/models.py
from django.db import models

# Create your models here.
class Users(models.Model):
    name=models.CharField(max_length=30)
    pwd=models.CharField(max_length=100)
    email=models.CharField(max_length=30)
    salt=models.CharField(max_length=100)
    is_active=models.BooleanField(default=False)
    class Meta:
        db_table='tb_users'

userapp/views.py
import hashlib
import random
import string
import traceback
import uuid

from django.core.mail import send_mail
from django.db import transaction
from django.http import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from itsdangerous import TimedJSONWebSignatureSerializer as serializer
# Create your views here.
from EFF import settings
from userapp.captcha.image import ImageCaptcha
from userapp.models import Users


def register(request):
    return render(request,'userapp/register.html')

def register_logic(request):
    try:
        name=request.POST.get('user_name')
        pwd=request.POST.get('pwd')
        cpwd=request.POST.get('cpwd')
        email=request.POST.get('email')
        allow=request.POST.get('allow')
        #密码加盐
        salt=str(uuid.uuid4())
        ha=hashlib.sha256()
        new_pwd=pwd + salt
        ha.update(new_pwd.encode())
        rst=ha.hexdigest()
        if pwd==cpwd and allow:
            rst1=Users.objects.create(name=name,pwd=rst,email=email,salt=salt)
            if rst1:
                id=rst1.id
                ser=serializer(settings.SECRET_KEY,expires_in=180)
                s=ser.dumps({'id':id}).decode()
                try:
                    send_mail('账户激活','http://127.0.0.1:8000/userapp/active/?token='+s,'752217726@qq.com',['78798465@qq.com'])
                    return JsonResponse({'msg':'注册成功,请等待管理员激活账户','status':1})
                except:
                    return JsonResponse({'msg':'发送邮件失败','status':0})
            else:
                return JsonResponse({'msg':'注册失败','status':0})
    except:
        return JsonResponse({'msg':'注册失败','status':0})

#检查注册的用户名是否存在
def check_name(request):
    name=request.POST.get('name')
    print(name)
    if Users.objects.filter(name=name):
        return HttpResponse('error')
    return HttpResponse('ok')


#生成验证码图片
def setImage(request):
    # 1.使用ImageCaptcha
    img=ImageCaptcha()
    # 2.生成随机码 大小写数字
    rst=random.sample(string.ascii_letters+string.digits,5)  #列表
    # 3.完成最终验证码图片
    # 对  列表进行 转换 成字符串
    code=''.join(rst)
    request.session['randcode']=code
    data=img.generate(code)
    return HttpResponse(data,'image/jpg')

# 验证逻辑
def captch_logic(request):
    rst = request.GET.get('val')
    print(rst)
    sessioncode = request.session.get('randcode')
    print(rst.lower(),sessioncode.lower())
    if rst.lower() == sessioncode.lower():
        return HttpResponse('验证成功')
    return HttpResponse('error')


def login(request):
    rst1 = request.COOKIES.get('user')
    rst2 = request.COOKIES.get('pwd')
    print(rst1,rst2)
    if rst1 and rst2:
        request.session['login']=True
        return redirect('operations:show')
    return render(request,'userapp/login.html')

def login_logic(request):
    try:
        name=request.POST.get('username')
        rst=Users.objects.filter(name=name)
        rem = request.POST.get('rem')
        print(rem)
        if rst:
            obj=rst[0]
            if obj.is_active:
                request.session['login'] = True
                pwd=request.POST.get('pwd')
                salt=obj.salt
                ha = hashlib.sha256()
                new_pwd = pwd + salt
                ha.update(new_pwd.encode())
                if ha.hexdigest() == obj.pwd:
                    res=JsonResponse({'msg':'登录成功','status':1})
                    if rem:
                        res.set_cookie('user','true',max_age=7*24*3600)
                        res.set_cookie('pwd','true',max_age=7*24*3600)
                    return res
                else:
                    return JsonResponse({'msg':'用户名或密码有误!','status':0})
            else:
                return JsonResponse({'msg':'该账户未做激活','status':-1})
        else:
            return JsonResponse({'msg':'用户名或密码有误!','status':0})
    except:
        return JsonResponse({'msg': '登录 失败', 'status': 0})


def forget_pwd(request):
    return render(request,'userapp/forget_pwd.html')

#忘记密码处理逻辑
def forget_pwd_logic(request):
    try:
        name=request.POST.get('user_name')
        email=request.POST.get('email')
        user=Users.objects.filter(name=name,email=email)
        print(user)
        if user:
            #邮件内容加密
            id=user[0].id
            ser=serializer(settings.SECRET_KEY,expires_in=180)
            s=ser.dumps({'id':id}).decode()
            try:
                #发送邮件
                send_mail('忘记密码','http://127.0.0.1:8000/userapp/resetpwd/?token='+s,'752217726@qq.com',['78798465@qq.com'])
                return JsonResponse({'msg': '发送忘记密码邮件成功,请等待管理员审核', 'status': 1})
            except:
                return JsonResponse({'msg': '用户或者邮箱不存在,请重新输入', 'status': 0})
        else:
            return JsonResponse({'msg': '用户或者邮箱不存在,请重新输入', 'status': 0})
    except:
        traceback.print_exc()
        return JsonResponse({'msg': '用户或者邮箱不存在,请重新输入', 'status': 0})

def reset_pwd(request):
    token=request.GET.get('token')
    print(token)
    try:
        ser = serializer(settings.SECRET_KEY, expires_in=180)
        user_id = ser.loads(token).get("id")
        print(user_id)
        if Users.objects.filter(pk=user_id):
            request.session['user_id'] = user_id
            return render(request, 'userapp/reset_pwd.html')
        return HttpResponse('token无效！')
    except:
        return HttpResponse('不好意思，链接已经失效！')

#重置密码处理逻辑
def reset_pwd_logic(request):
    user_id=request.session.get('user_id')
    try:
        rst = Users.objects.get(pk=user_id)
        print(rst)
        pwd=request.POST.get('user-pwd')
        print(pwd)
        pwd1=request.POST.get('confirm-pwd')
        if pwd == pwd1:
            try:
                if rst:
                    with transaction.atomic():
                        #密码加盐
                        ha = hashlib.sha256()
                        salt = rst.salt
                        new_pwd = pwd + salt
                        ha.update(new_pwd.encode())
                        rst.pwd = ha.hexdigest()
                        rst.save()
                        del request.session['user_id']
                        print(rst.pwd)
                        return JsonResponse({'msg': '重置密码成功，即将回到登陆页面', 'status': 1})
                else:
                    return JsonResponse({'msg': '重置密码失败', 'status': 0})
            except:
                traceback.print_exc()
                return JsonResponse({'msg': '重置密码失败', 'status': 0})
        else:
            return JsonResponse({'msg': '两次输入不一致', 'status': 0})
    except:
        traceback.print_exc()
        return JsonResponse({'msg': '重置密码失败', 'status': 0})

def home(request):
    status=request.session.get('login')
    if status:
        return render(request, 'operations/home.html')
    return redirect('userapp:login')

def logout(request):
    return render(request,'userapp/logout.html')

# 激活视图函数
def active(request):
    # 1.激活账户
    # 2.数据库查询该条数据(接收),修改is_active 字段值 修改成True，并保存，则激活成功
    temp_s=request.GET.get('token')
    # 解密 得到id
    ser = serializer(settings.SECRET_KEY, expires_in=180)
    s = ser.loads(temp_s)  #反序列化之后是一个字典 取键值
    print(s.get('id'))
    rst=Users.objects.filter(id=s.get('id'))
    if rst:
        obj=rst[0]
        if obj.is_active:
            return HttpResponse('该账户'+ str(obj.name) + '已经审核过了!')
        else:
            obj.is_active=True
            obj.save()
            return HttpResponse('恭喜'+ str(obj.name) + '账户成功激活!')

def reactive(request):
    try:
        name=request.GET.get('username')
        user=Users.objects.get(name=name)
        id=user.id
        print(id)
        ser = serializer(settings.SECRET_KEY, expires_in=180)
        s = ser.dumps({'id': id}).decode()
        send_mail('账户激活', 'http://127.0.0.1:8000/userapp/active/?token=' + s, '752217726@qq.com', ['78798465@qq.com'])
        return JsonResponse({'msg':'发送激活邮件成功','status':1})
    except:
        traceback.print_exc()
        return JsonResponse({'msg':'发送激活邮件失败','status':0})

templates/userapp/forget_pwd.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    {% load static %}
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>EFF超市管理系统-忘记密码</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/register.js"></script>
	<style>
		.reg_form {
			margin:65px 0 0 30px;
		}
	</style>
</head>
<body>
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/EFF-logo.jpg" width="230px" height="70px"></a>
			<div class="reg_slogan">美好生活，乐享乐购。</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>密码找回</h1>
			</div>
			<div class="reg_form clearfix">
				<form action="{% url 'userapp:forgetpwdlogic' %}" method="post">
                    {% csrf_token %}
                    <ul>
                        <li>
                            <label>用户名:</label>
                            <input type="text" name="user_name" id="user_name">

                        </li>
                        <li>
                            <label>邮箱:</label>
                            <input type="text" name="email" id="email">
                            <span class="error_tip">提示信息</span>
                        </li>

                        <li class="reg_sub">
                            <input type="submit" value="提交" name="" onblur="forget_submit()">
                        </li>
                    </ul>
				</form>
			</div>

		</div>

	</div>
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
        function forget_submit() {
            $.ajax({
                type:'post',
                url:'{% url 'userapp:forgetpwdlogic' %}',
                data:$('form').serialize(),
                success:function (data) {
                     if (data.status ===1){
                         alert(data.msg);
                         location.href="{% url 'userapp:login' %}";
                     }else {
                         alert(data.msg);
                     }
                 }
            })
        }
    </script>
	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2020 上知天文下知科技有限公司 All Rights Reserved</p>
		<p>电话：010-****888    豫ICP备*******8号</p>
	</div>
	
</body>
</html>

templates/userapp/login.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    {% load static %}
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>EFF超市管理系统-登录</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo" style="font-size: 30px;">
            <img src="/static/images/EFF-logo.jpg" width="230px" height="70px">
            <span style="color:black;font-size: 15px;">美好生活，乐享乐购。</span>
        </a>
	</div>

	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">EFF超市管理系统</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'userapp:register' %}">立即注册</a>
				</div>
				<div class="form_input">
					<form action="{% url 'userapp:loginlogic' %}" method="post">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="rem" value="ok">
							<label>7天自动登录</label>
							<a href="{% url 'userapp:forget_pwd' %}">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit" onclick="login_form()">
					</form>
				</div>
			</div>
		</div>
	</div>
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
        function login_form() {
             $.ajax({
                 type:'POST',
                 url:'{% url 'userapp:loginlogic' %}',
                 data:$('form').serialize(),
                 success:function (data) {
                     if (data.status ===1){
                         alert(data.msg);
                         location.href="{% url 'operations:show' %}";
                     }else if (data.status === -1){
                         var boo=window.confirm('是否要重新发送邮件进行激活？');
                         if (boo){
                             location.href="{% url 'userapp:reactive' %}?username=" + $('[name="username"]').val();
                         }
                     }
                     else {
                         alert(data.msg);
                     }
                 }
             });
         }
    </script>
	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2020 上知天文下知科技有限公司 All Rights Reserved</p>
		<p>电话：010-****888    豫ICP备*******8号</p>
	</div>
	
</body>
</html>

templates/userapp/register.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    {% load static %}
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>EFF超市管理系统-注册</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/register.js"></script>
</head>
<body>
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/EFF-logo.jpg" width="230px" height="90px"></a>
			<div class="reg_slogan">美好生活，乐享乐购。</div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>用户注册</h1>
				<a href="{% url 'userapp:login' %}">登录</a>
			</div>
			<div class="reg_form clearfix">
				<form action="{% url 'userapp:registerlogic' %}" method="post">
                    {% csrf_token %}
				<ul>
					<li>
						<label>用户名:</label>
						<input type="text" name="user_name" id="user_name" placeholder="请输入真实姓名" onblur="checkname()">
                        <a href=""></a><span></span>
						<span class="error_tip">提示信息</span>
					</li>					
					<li>
						<label>密码:</label>
						<input type="password" name="pwd" id="pwd" placeholder="请输入密码">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="cpwd" id="cpwd" placeholder="请输入确认密码">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
						<label>邮箱:</label>
						<input type="text" name="email" id="email" placeholder="请输入邮箱">
						<span class="error_tip">提示信息</span>
					</li>
					<li>
                        <label>验证码:</label>
                        <input type="text" name="captcha" id="captcha" onblur="check()" style="width: 100px;">
                        <img src="{% url 'userapp:setimg' %}" alt="" width="80">
                        <a href="javascript:void(0);" style="text-decoration: underline;">看不清，换一张</a><span></span>
                        <span class="error_tip" id="tip_captcha">提示信息</span>
                    </li>
					<li class="agreement">
						<input type="checkbox" name="allow" id="allow" checked="checked">
						<label>同意”EFF超市管理系统使用协议“</label>
						<span class="error_tip2">提示信息</span>
					</li>
					<li class="reg_sub">
						<input type="button" value="注 册" name="" onclick="submit_form()">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>

	<div class="footer no-mp">
		<div class="foot_link">
			<a href="http://www.baidu.com">关于我们</a>
			<span>|</span>
			<a href="http://www.baidu.com">联系我们</a>
			<span>|</span>
			<a href="http://www.baidu.com">招聘人才</a>
			<span>|</span>
			<a href="http://www.baidu.com">友情链接</a>
		</div>
		<p>CopyRight © 2020 上知天文下知科技有限公司 All Rights Reserved</p>
		<p>电话：010-****888    豫ICP备*******8号</p>
	</div>
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
        function check() {
         //发送ajax请求 get请求
        //1.创建核心工作对象
            var xhr = null;
            if (window.XMLHttpRequest) {
                xhr = new XMLHttpRequest();
            } else if (window.ActiveXObject) {
                xhr = new ActiveXObject('Microsoft.XMLHTTP');
            }
            //2.发送请求前 配置工作
            // url + 拼接参数  ?键值对
            var inp=document.getElementsByName('captcha')[0].value;
            var url='{% url 'userapp:captchlogic' %}?val='+inp;
            xhr.open('get',url);
            //3. 发送请求
            xhr.send();
            //验证码验证过程中 显示loading效果
            //4.服务器进行业务处理 是否处理完毕，客户端是否可接收
            //通过事件去监听
            xhr.onreadystatechange = function () {
                //console.log(xhr.readyState);
                if (xhr.readyState === 4 && xhr.status === 200) {
                    console.log(xhr.responseText);
                    var res = xhr.responseText;
                    var sp = document.getElementsByTagName('span')[5];
                    //sp.innerHTML = xhr.responseText;
                    if (res === '验证成功') {
                        //显示在span内图片
                        sp.innerHTML = "<img src='{% static "images/right.jpg" %}' style='width:20px' />";
                    }
                    else {
                        sp.innerHTML = "<img src='{% static "images/error_3.jpg" %}' style='width:20px' />";
                    }
                }
            }
        }
        var a=document.getElementsByTagName('a')[3];
        a.onclick=function () {
            var img=document.getElementsByTagName('img')[1];
            img.src='{% url 'userapp:setimg' %}?time='+new Date().getTime();
        };
         function submit_form() {
             $.ajax({
                 type:'post',
                 url:'{% url 'userapp:registerlogic' %}',
                 data:$('form').serialize(),
                 success:function (data) {
                     if (data.status ===1){
                         alert(data.msg);
                         location.href="{% url 'userapp:login' %}";
                     }else {
                         alert(data.msg);
                     }
                 }
             });
         }
         function checkname(){
            //发送ajax请求 get请求
            //1.创建核心工作对象
            var xhr = null;
            if (window.XMLHttpRequest) {
                xhr = new XMLHttpRequest();
            } else if (window.ActiveXObject) {
                xhr = new ActiveXObject('Microsoft.XMLHTTP');
            }
            //2.发送请求前 配置工作
            //url 单独书写，传送参数单独发送
            var url = '{% url "userapp:checkname" %}';
            xhr.open('POST',url);
            //3.发送请求 send() 参数 需要发送给服务器数据
            //send(string) 键值对形式
            //发送请求之前，设置请求头 模拟表单
            xhr.setRequestHeader('Content-type','application/x-www-form-urlencoded');
             // 获取当前输入框内的值
            var val=document.getElementsByName('user_name')[0].value;
            //设置 csrftoken令牌
            xhr.send('name=' + val + '&csrfmiddlewaretoken={{ csrf_token }}');
            //4。服务器处理请求 前端接收响应
            xhr.onreadystatechange = function () {
                if (xhr.readyState === 4 && xhr.status === 200) {
                    console.log(xhr.responseText);
                    var res = xhr.responseText;
                    var sp = document.getElementsByTagName('span')[0];
                    if (res === 'ok') {
                        //显示在span内图片
                        sp.innerHTML = "恭喜用户名可以使用";
                    }
                    else {
                        sp.innerHTML = "用户名重复，不可使用";
                    }
                }
            }
         }
    </script>
</body>
</html>

templates/userapp/reset_pwd.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    {% load static %}
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>EFF超市管理系统-重置</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/register.js"></script>
	<style>
		.reg_form {
			margin:65px 0 0 30px;
		}
	</style>
</head>
<body>
	<div class="register_con">
		<div class="l_con fl">
			<a class="reg_logo"><img src="/static/images/EFF-logo.jpg" width="230px" height="90px"></a>
			<div class="reg_slogan">美好生活，乐享乐购。</div>
			<div class="reg_banner"></div>
		</div>

		<div class="r_con fr">
			<div class="reg_title clearfix">
				<h1>重置密码</h1>
			</div>
			<div class="reg_form clearfix">
				<form action="{% url 'userapp:resetpwdlogic' %}" method="post">
                    {% csrf_token %}
				<ul>
					<li>
						<label>输入密码:</label>
						<input type="password" name="user-pwd" id="user_pwd">

					</li>
					<li>
						<label>确认密码:</label>
						<input type="password" name="confirm-pwd" id="confirm-pwd">

					</li>

					<li class="reg_sub">
						<input type="submit" value="提交" name="" onclick="sumbit_reset()">
					</li>
				</ul>				
				</form>
			</div>

		</div>

	</div>
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
        function sumbit_reset(){
                $.ajax({
                type : "post",
                url : "{% url 'userapp:resetpwdlogic' %}",
                data:$('form').serialize(),
                success : function (data){
                    if (data.status===1){
                        alert(data.msg);
                        location.href='{% url "userapp:login" %}';
                    }else{
                        alert(data.msg);
                    }
                }
            });
            }
    </script>
	<div class="footer no-mp">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>		
		</div>
		<p>CopyRight © 2020 上知天文下知科技有限公司 All Rights Reserved</p>
		<p>电话：010-****888    豫ICP备*******8号</p>
	</div>
	
</body>
</html>